name: mindlink_assignment
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.0
  share_plus: ^10.0.0
  video_player: ^2.9.1
  chewie: ^1.8.4
  change_app_package_name: ^1.3.0
  http: ^1.2.2
  uni_links2: ^0.6.0+2
  firebase_core_web: ^2.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Codename Red.webp
    - assets/Assassins Creed Flag Live Wallpaper.mp4
