// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMcVYeL1ZnGYibUUPVU8Hun_RC1mbrMP8',
    appId: '1:395881504713:web:e025d4e2b9715c11859218',
    messagingSenderId: '395881504713',
    projectId: 'mindlink-assignment-cf40b',
    authDomain: 'mindlink-assignment-cf40b.firebaseapp.com',
    storageBucket: 'mindlink-assignment-cf40b.appspot.com',
    measurementId: 'G-0NSTQ5NRGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyrPcZ3PTOEqkD14CUb8U-ZNanEjSRobo',
    appId: '1:395881504713:android:837f351b08eb3b70859218',
    messagingSenderId: '395881504713',
    projectId: 'mindlink-assignment-cf40b',
    storageBucket: 'mindlink-assignment-cf40b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM5fJPh2cKcTYsgax2eU0aI_ujRlwGNnE',
    appId: '1:395881504713:ios:ef29bb963459ab57859218',
    messagingSenderId: '395881504713',
    projectId: 'mindlink-assignment-cf40b',
    storageBucket: 'mindlink-assignment-cf40b.appspot.com',
    iosBundleId: 'com.task',
  );
}
